version: '3'

vars:
  TEST_SHORT: '{{.TEST_SHORT | default "true"}}'
  TEST_PACKAGE: '{{.TEST_PACKAGE | default "./..."}}'
  TEST_COVERAGE: '{{.TEST_COVERAGE | default "/tmp/chester.cov"}}'
  TEST_VERBOSE: '{{.TEST_VERBOSE | default "false"}}'

tasks:
  run:
    cmds:
      - go run . {{.CLI_ARGS}}

  lint:
    cmds:
      - go vet {{.CLI_ARGS}}

  test:
    cmds:
      - go test -coverprofile={{.TEST_COVERAGE}} -short={{.TEST_SHORT}} -v={{.TEST_VERBOSE}} {{.TEST_PACKAGE}}

  test-coverage:
    deps: [test]
    cmds:
      - go tool cover -func={{.TEST_COVERAGE}}

  test-coverage-html:
    deps: [test]
    cmds:
      - go tool cover -html={{.TEST_COVERAGE}}
