version: "3"

tasks:
  default:
    cmds:
      - go run .

  profile:
    cmds:
      - mkdir -p tmp/profiles
      - go run . --profile=$(mktemp tmp/profiles/chester-XXXX.pprof)
  test:
    cmds:
      - mkdir -p tmp/tests
      - go test -short -race -coverprofile=tmp/tests/coverprofile ./...
      - go tool cover -func=tmp/tests/coverprofile

  perftree:
    cmds:
      - perftree scripts/perft.sh

  docker:
    cmds:
      - docker build -t chester:latest -f docker/Dockerfile .

  deploy:
    cmds:
      - fly deploy

  compare:
    requires:
      vars: [OLD]
    cmds:
      - scripts/compare.sh {{ .OLD }} {{ .NEW }}
